### PR TITLE
Added a new table with a development emision line table

### PR DESCRIPTION
**Pull request by alxogm**
It currently  modifies only the continuum in the Lya and Lyb region. This preserves better the colors in select_mock_targets. Other changes are only to make sure we can still use the current model in quickquasars.

### CODE REVIEW

**Comment by alxogm** [comment]
Thanks @andreufont and @moustakas .  I think failures are not due to this PR, but still I'll merge as soon as tests passes.

**Comment by alxogm** [comment]
Hi @moustakas, @sbailey ,  can you help me here? I don't know why tests are not passing. Errors seems to be when loading the unittests and astropy... 

any idea how can I fix it? we would like to merge this soon. 

Thanks!

`ERROR: desisim.test.test_batch (unittest.loader._FailedTest)
2396----------------------------------------------------------------------
2397ImportError: Failed to import test module: desisim.test.test_batch
2398Traceback (most recent call last):
2399  File "/home/travis/miniconda/envs/test/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
2400    module = self._get_module_from_name(name)
2401  File "/home/travis/miniconda/envs/test/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
2402    __import__(name)
2403  File "/home/travis/build/desihub/desisim/py/desisim/test/test_batch.py", line 5, in <module>
2404    from desisim.batch.pixsim import batch_newexp, batch_pixsim
2405  File "/home/travis/build/desihub/desisim/py/desisim/batch/pixsim.py", line 32, in <module>
2406    from desisim import obs
2407  File "/home/travis/build/desihub/desisim/py/desisim/obs.py", line 28, in <module>
2408    import desisim.simexp
2409  File "/home/travis/build/desihub/desisim/py/desisim/simexp.py", line 13, in <module>
2410    freeze_iers()
2411  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/desisurvey/utils.py", line 117, in freeze_iers
2412    raise RuntimeError('Frozen IERS is not installed as the default.')
2413RuntimeError: Frozen IERS is not installed as the default.`

`astropy=4.0 -> numpy[version='>=1.16|>=1.16.5,<2.0a0']
2301astropy=4.0 -> pytest-astropy -> pytest-arraydiff[version='>=0.1'] -> numpy[version='>=1.10']
2302
2303Installing astropy with conda was unsuccessful, using pip instead
2304ERROR: Could not find a version that satisfies the requirement astropy==4.0 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3, 0.3.1, 0.3.2, 0.4rc1, 0.4rc2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.1b1, 1.1rc1, 1.1rc2, 1.1, 1.1.post1, 1.1.post2, 1.1.1, 1.1.2, 1.2rc1, 1.2, 1.2.1, 1.2.2, 1.3rc1, 1.3, 1.3.1, 1.3.2, 1.3.3, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 3.0rc1, 3.0rc2, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1rc1, 3.1rc2, 3.1, 3.1.1, 3.1.2, 3.2rc1, 3.2rc2, 3.2, 3.2.1, 3.2.2, 3.2.3)
2305ERROR: No matching distribution found for astropy==4.0
Top`

**Comment by sbailey** [comment]
@weaverba137 can you help with both this frozen IERS test failure and the astropy installation failure?  Note that this dev_continuum branch was made after the freeze-iers branch was merged in PR #520.  Thanks.

**Comment by weaverba137** [comment]
So, desisim/desisurvey are not compatible with astropy 4.0.  It would appear that there is some change to astropy's IERS code that needs to be examined.  Astropy 2.0.16 still works.

Unrelated to the actual error, but note that it is becoming increasingly difficult (and time-consuming) to find compatible package sets for Python 3.5.

**Comment by sbailey** [comment]
Green light to drop python 3.5 support across all desi packages.  Let's retain 3.6 compatibility though (i.e. not yet use 3.7-only features).

**Comment by alxogm** [comment]
@sbailey @weaverba137 many thanks! 
Tests have passed so I'm merging now.

**Pull request merged**
