### PR TITLE
Fiberassign xy

### PR DESCRIPTION
**Pull request by sbailey**
This PR is a companion to desihub/desispec#821 to handle the renaming of DESIGN_X/Y -> FIBERASSIGN_X/Y.  I'm still testing at NERSC with the minitest notebook, but I'm opening this PR now to get Travis testing going too.

### CODE REVIEW

**Comment by weaverba137** [comment]
Interesting!  astropy/ci-helpers has recently added some code that tries to interpret version numbers, and it may be choking on the NUMPY_VERSION.

**Comment by weaverba137** [comment]
See astropy/ci-helpers#422

**Comment by weaverba137** [comment]
I think the problem is fixed, but I'm now seeing network errors during the install phase.  Stay tuned.

**Comment by weaverba137** [comment]
O boy, what a mess, it looks like on Python 3.5, pip is uninstalling numpy, leaving no valid numpy version.  On Python 3.6, tests are failing due to genuine key errors, not install problems.

**Comment by weaverba137** [comment]
I've found a numpy version that works for Python 3.5, but it's time to think about abandoning 3.5 altogether.  All test failures are now due to genuine key errors.  Over to you @sbailey.

**Comment by sbailey** [comment]
Thanks for working on this.  The FIBERASSIGN_X key error when testing under 3.6 is because it needs the changes in desihub/desispec#821.  If you can get the python 3.5 tests back into a state of failing on genuine test errors and not on pip/numpy/etc installation problems, I'll run with the rest.

For the record, tests pass on my laptop using desisim/fiberassign_xy + desispec/fibermap_xy + master of everything else, and python 3.6.7 + numpy 1.16.4.  At NERSC tests pass with the same versions of desi code + python 3.6.6 + numpy 1.16.4.

**Comment by sbailey** [comment]
Thanks!  The next time 3.5 becomes problematic, let's drop it, while still trying to retain support for python 3.6 through 3.8 (which just came out).

I tagged desispec/0.30.0 (long overdue) and am testing this branch against that now in prep for merging and a new desisim tag.

**Pull request merged**
