### PR TITLE
Revert "Qqso dla bal"

### PR DESCRIPTION
**Pull request by alxogm**
Reverts desihub/desisim#371
To see why travis is failing

### CODE REVIEW

**Comment by alxogm** [comment]
@moustakas Travis failed again, but only once instead of twice.. It says it could be a spurious error and try to commit again. Should I make this merge pull? This, supposedly will revert the master brach to where it was before my merge, right? 

"A remote server error occurred when trying to retrieve this URL.
A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server."

**Comment by moustakas** [comment]
I'm sorry, I don't know.  @sbailey and/or @weaverba137 may be able to help.

**Comment by weaverba137** [comment]
The error is happening in the conda install stage, before desisim is even tested.  Note that one of the tests *did* pass.  I recommend restarting the failed job.

**Comment by alxogm** [comment]
@julienguy the issue with Travis was fixed, don't know exactly why. So you let me know if I should complete this PR or what to do. I won't do anything until you tell me

**Comment by alxogm** [comment]
@weaverba137 thanks, it seems it was restarted automatically and not it is ok.

**Comment by julienguy** [comment]
I restarted the test about an hour ago :-)

**Comment by alxogm** [comment]
@julienguy Thanks!

**Comment by julienguy** [comment]
I am merging this branch because master quickquasars is broken

**Comment by alxogm** [comment]
Ok,  I'll wait until everything is in green, then update my repository and then try again my PR, asking for your green light!

**Pull request merged**
