### PR TITLE
clobber -> overwrite

### PR DESCRIPTION
**Pull request by sbailey**
This PR converts `astropy.io.fits` argument `clobber` to `overwrite` to avoid deprecation warnings.

### CODE REVIEW

**Comment by sbailey** [comment]
In general we've been keeping the travis dependencies as the oldest known versions that work, and let the nightly cronjob tests at NERSC test the latest version of each package against each other.  It's fine to update the travis dependencies when we know that we're making a change that requires a newer version, but as long as the tests pass I consider it somewhat of a feature when travis is checking old versions given that NERSC cronjobs are checking new versions.  Note that the recent minitest notebook integration tests problems wouldn't have been caught by the current unit tests at all, with old or new dependencies.

Travis had a few hiccups when running tests yesterday; restarting those jobs now and I'll fix any remaining tests if things fail again.

**Comment by weaverba137** [comment]
@sbailey, in general I agree, but weren't there some significant changes in desimodel in 18.6?  Also, it looks like desisim is testing against the full desimodel download, instead of the testing branch.

**Comment by sbailey** [comment]
Good point.  I'll update desimodel tests to use the latest testing branch (that also explains why desisim tests have become so slow again on Travis...)

**Comment by sbailey** [comment]
Updated to desimodel test-0.9.6 and confirmed that the test logs no longer have the clobber deprecation warning.  @weaverba137 any other blocking issues or ok to merge?

**Pull request merged**
