### PR TITLE
Migrate desisim to GitHub Actions

### PR DESCRIPTION
**Pull request by weaverba137**
This PR migrates desisim to use GitHub Actions instead of Travis CI for unit tests.

While testing, a version of #507 reappeared, although this time it is complaining of suspiciously low *ELG* or *LRG* flux.

See [this run](https://github.com/desihub/desisim/actions/runs/529377843) for full details.

Oddly though, #534 did not reappear.  Perhaps that was a red-herring and desimodel/branches/test-0.12 does have the fix installed.

### CODE REVIEW

**Comment by sbailey** [comment]
FYI #547 documents the pixsim test failure and likely cause (a change in specter, but requiring a non-negative input flux cut in desisim).  We could proceed with this PR even if that test is still failing.

The "suspiciously low XYZ flux" problem appears occasionally in the nightly tests and previously travis tests; I usually ignore and rerun.

**Comment by weaverba137** [comment]
OK, the tests were successful after a restart, but I still think the low flux problem should actually be fixed, not ignored.  In particular, experts know to restart the tests, but newcomers would have to be aware that this is a known issue.

**Comment by weaverba137** [comment]
PS, I still have a few minor changes to make to this PR, like removing the `.travis.yml` file, so please don't merge immediately.

**Review by sbailey — APPROVED** [review]
This PR looks good, thanks.  Merge when ready.  I agree that the low flux bug should be fixed, but it doesn't need to be a blocking factor for this travis -> github actions transition.

**Comment by weaverba137** [comment]
@sbailey, thank you merging very soon.

**Comment by weaverba137** [comment]
Test failures are related to #507, ignoring.

**Pull request merged**
