### PR TITLE
Quickgen

### PR DESCRIPTION
**Pull request by rstaten**
This PR

- Adds keyword --frameonly to quickgen.

- Gives quickgen the option to only output uncalibrated frame files.

### CODE REVIEW

**Comment by sbailey** [comment]
This is a good feature to add, but this implementation involves a lot of replicated code.  Could you implement this with something like:
```
loop over exposures:
    [simulate frames]
    if frameonly:
        continue
    else:
        [simulate sky, stdstars, cframe, etc.]
```
i.e. the code for simulating a frame should be the exact same code whether or not --frameonly is selected, and then any non-frame code should just be skipped if it isn't needed.

**Comment by rstaten** [comment]
The most recent commit fixes this.

**Comment by sbailey** [comment]
Thanks.  Now it is just 3 lines of code instead of N>>1 new lines, and changing anything in how frames are generated will automatically worth with and without --frameonly.

**Comment by moustakas** [comment]
Very excited to see these kinds of developments, @rstaten, thank you.

**Comment by rstaten** [comment]
@moustakas No problem. Let me know if there is something you would like to see implemented.

**Pull request merged**
