### PR TITLE
Run quickquasars with eBOSS option

### PR DESCRIPTION
**Pull request by belaa**
This PR allows the option to run desisim using the 'eBOSS' configuration of specsim. It is motivated by the studies described in Issue #437. 

Note: The PR for the specsim sdss (eBOSS) config is pending approval, so that would need to occur before we can move forward with this PR.

### CODE REVIEW

**Comment by belaa** [comment]
I meant to include above: successfully running the eBOSS version also requires adding a FITS file to desimodel for fiber positions within the eBOSS field radius (to be read by `desimodel.io.load_fiberpos()`, which is called in `simexp.simulate_spectra()`). I believe @londumas is already doing this.

**Comment by londumas** [comment]
@sbailey, it trigered an error that does not seem related to the branch:
```
ok
test_wd_subtype_failure (desisim.test.test_templates.TestTemplates)
Test a known failure of specifying the white dwarf subtype. ... In function test_wd_subtype_failure, seed = 2460073889
INFO:io.py:956:read_basis_templates: Reading /home/travis/build/desihub/desisim/desisim-testdata-0.6.1/desi/spectro/templates/basis_templates/v3.0/wd_templates_v2.1-lite.fits
WARNING:templates.py:1785:make_templates: WD Class initialized with subtype DA, which does not match input table.
expected failure
test_version (desisim.test.test_top_level.TestTopLevel)
Ensure the version conforms to PEP386/PEP440. ... ok
======================================================================
FAIL: test_newexp (desisim.test.test_obs.TestObs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desisim/py/desisim/test/test_obs.py", line 103, in test_newexp
    self.assertTrue(maxflux > 0.01, 'suspiciously low {} flux ({}) using seed {}; wrong units?'.format(objtype, maxflux, seed))
AssertionError: False is not true : suspiciously low ELG flux (0.0) using seed 790803567; wrong units?
```

**Comment by londumas** [comment]
@sbailey, thanks for the help.

**Comment by sbailey** [comment]
Travis test failure was indeed an unrelated problem that randomly crops up when simulating ELGs for the tests.  I restarted Travis.

Code here looks fine.  It looks like it only requires the eboss config and the update specsim if running quickquasars for eboss (i.e. it doesn't break DESI usage), so I'm fine with merging this now (after Travis finishes), or waiting for specsim et al to be updated too.

**Comment by londumas** [comment]
@sbailey, thank you very much. Let's wait for specsim to be merged. I will go ahead and do it myself when ready.

**Comment by sbailey** [comment]
Now Travis is failing after the code installation, before it even gets to running the tests.  I'll wait and try the tests again later.

**Comment by londumas** [comment]
@sbailey, I merged it with master to trigger new tests, and it fails there, which still does not look like our bad job:
```
test_wd_subtype_failure (desisim.test.test_templates.TestTemplates)
Test a known failure of specifying the white dwarf subtype. ... In function test_wd_subtype_failure, seed = 2460073889
INFO:io.py:956:read_basis_templates: Reading /home/travis/build/desihub/desisim/desisim-testdata-0.6.1/desi/spectro/templates/basis_templates/v3.0/wd_templates_v2.1-lite.fits
WARNING:templates.py:1785:make_templates: WD Class initialized with subtype DA, which does not match input table.
expected failure
test_version (desisim.test.test_top_level.TestTopLevel)
Ensure the version conforms to PEP386/PEP440. ... ok
======================================================================
FAIL: test_multiobs (desisim.test.test_quickcat.TestQuickCat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desisim/py/desisim/test/test_quickcat.py", line 169, in test_multiobs
    self.assertGreater(n1, n2)
AssertionError: 235 not greater than 238
----------------------------------------------------------------------
Ran 63 tests in 243.703s
FAILED (failures=1, expected failures=1)
```

**Comment by andreufont** [comment]
Hi everyone - what is the status of this pull request? Also, does this include the log(lambda) binning used in SDSS, or does it still use bins constant in lambda (like DESI)?
Thanks!

**Comment by londumas** [comment]
@andreufont, the status is that we are waiting for reviews in desisim and specsim.

**Comment by andreufont** [comment]
Who are the reviewers? Are they aware of it?

**Comment by sbailey** [comment]
I'm patching up the Travis testing, but am otherwise find for this to be merged, either before or after desihub/specsim#100 as long as this doesn't break the DESI usage (I see a comment over there about a hardcoded `specsim_config_file="eboss"` which sounds a bit scary, but I didn't dig deeper).

**Comment by sbailey** [comment]
Are we all waiting for each other here?  Is there any reason not to merge this PR now?  I'm fine with it as is.  Any objections @londumas @belaa @andreufont others?

**Comment by andreufont** [comment]
Hi @sbailey - @belaa and @londumas worked on this during the hack day, but I believe they did not finish the work they work doing... they should comment on this.

**Comment by belaa** [comment]
@sbailey Sorry for late response was out of town and off email - no objections from me.

**Comment by moustakas** [comment]
Is this PR still active / valid? @belaa

**Comment by belaa** [comment]
@moustakas Yes! It is ready for review, when you get a chance...

**Comment by moustakas** [comment]
@sbailey and @londumas have already approved, but I took a look and the changes look good!

But could you please update the change log? And then please feel free to self-merge.

**Pull request merged**
