### PR TITLE
Eboss quickquasars

### PR DESCRIPTION
**Pull request by londumas**
Add the option in `quickquasars.py` to produce eBOSS like data:
- magnitude distribution
- footprint: inhomogeneities of the density and of the n(z)
- n(z)

Tested in `/project/projectdirs/desi/mocks/lya_forest/london/v4.0.0/eboss-0.2/` and it works very well.

histo_z

footprint

### CODE REVIEW

**Comment by londumas** [comment]
@andreufont and @moustakas, Doesn't pass the Travis tests, but it doesn't seem to be because of anything this PR does.

**Comment by moustakas** [comment]
@londumas Travis tests are failing in `test_quickquasars`, and this PR changed `quickquasars`, so you should please try to track down the problem (or update the unit test).

@andreufont For these types of "support" data files there are no data model or documentation requirements that I'm aware of (or have conformed to!), as long as it's clear where they're being used in the code.

**Comment by londumas** [comment]
@moustakas, I will have a look, thanks.
@andreufont, For what is worth, I have added in the header of the two files the description of the files used to produce them, and the options: nside, nest, ...

**Comment by londumas** [comment]
@moustakas, The issue was that the code was setting the magnitude limits to `None` to reach the default. Fixed now.

**Pull request merged**
