### PR TITLE
clean up of quickbrick to support bright-time survey

### PR DESCRIPTION
**Pull request by moustakas**
I'm opening this PR now so I can get  can get eyes on the code sooner rather than later. Algorithmically I haven't changed anything significant in ```quickbrick```, but I have done a thorough "cleaning" of the code (PEP8 style mostly throughout, streamlining of variables and repeat code, some error handling, refactoring into parse() and main() functions, additional optional inputs such as the lunar phase parameters, etc.).  The biggest change is that ```quickbrick``` can now be used to simulate bright-time objects via the BGS, MWS, or BRIGHT_MIX objtype optional input.

This PR should close the bug identified in #101 and should move us significantly closer toward generating the bright-time simulations we need (#72).  

Some outstanding issues I would still like to fix/add:
* Figure out the verbose logging (help on this would be great -- log.info prints output even when the debugging level isn't set to INFO)
* Add additional error checking
* Optionally output spectra with supernova spectra superposed (see #100)

### CODE REVIEW

**Comment by moustakas** [comment]
What should we do about testing high-level scripts like ```quickbrick```?  Although at its heart ```quickbrick``` is a wrapper script, there's plenty of stuff that could "go wrong" as the code is developed and changed (as in this PR).  We almost certainly want to know that the code is writing out consistent output, given identical input.  I'd like the answer to this question to not be part of this PR necessarily (to not bog it down), but I think that we do need to construct some set of tests, or at least refactor the code so its components can be tested.

**Comment by moustakas** [comment]
I believe this is in good enough shape that it's ready to merge.

**Comment by moustakas** [comment]
I see that my previous comment was discussed in #96.  I'll work on resolving this issue as part of this PR.

**Comment by sbailey** [comment]
Merging now; let's add tests in a separate PR.

**Pull request merged**
