### PR TITLE
update to v3.2 basis templates

### PR DESCRIPTION
**Pull request by moustakas**
In this PR I update `desisim.module` to use the `v3.2` basis templates, which are identical to `v3.1` except for the BAL templates, which were updated from `v2.1` to `v3.0` (see #504 and #509)--
  https://desi.lbl.gov/svn/data/basis_templates/tags/v3.2/

@jfarr03 @paulmartini let's hold off on merging this PR until the `19.9` software release is out.

At that point, @sbailey, you'll also need do some magical incantation at NERSC to use these updated basis templates and we'll also need to update the instructions on the wiki:
* https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata
* https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#Defineinputtemplatelocations

@paulmartini @jfarr03 any tests of `quickquasars` using these templates (which you can do by pointing your `DESI_BASIS_TEMPLATES` environment variable to `/global/projecta/projectdirs/desi/spectro/templates/basis_templates/v3.2`) is much appreciated.

In particular, note that we only read a subset of the available columns into the metadata table returned by `desisim.io.read_basis_templates`, although you may want additional columns returned--
https://github.com/desihub/desisim/blob/master/py/desisim/io.py#L980-L981

### CODE REVIEW

**Comment by moustakas** [comment]
@paulmartini @jfarr03 @sbailey can we merge this PR?  Should be pretty non-controversial.

**Comment by jfarr03** [comment]
@moustakas no objections from me!

**Comment by sbailey** [comment]
OK, merging now.  I got cold feet yesterday before the 19.10 release because new templates sometimes have unintended consequences with memory or runtimes and I didn't want to have to restart that testing from the beginning.

**Comment by sbailey** [comment]
For the record: I updated the master install at NERSC to use the new templates too:
```
[cori11 ~] source /project/projectdirs/desi/software/desi_environment.sh master
[cori11 ~] echo $DESI_BASIS_TEMPLATES 
/global/project/projectdirs/desi/spectro/templates/basis_templates/v3.2
[cori11 ~] ls $DESI_BASIS_TEMPLATES
README.rst               elg_templates_v2.2.fits  sne_templates_v1.1.fits      wd_templates_v2.2.fits
bal_templates_v3.0.fits  lrg_templates_v2.2.fits  star_templates_v3.1.fits
bgs_templates_v2.3.fits  qso_templates_v2.0.fits  stdstar_templates_v2.2.fits
```

**Pull request merged**
