### PR TITLE
Update eBOSS to DR16 footprint

### PR DESCRIPTION
**Pull request by londumas**
Update eBOSS to DR16 footprint, important for the DR16 production.
in DR14:

z-distrib

z-survey-DR14

in DR16:
z-distrib-dr16

z-survey-dr16

### CODE REVIEW

**Comment by alxogm** [comment]
Hmm It let me accepted the review with the wrong user... is this ok?

**Comment by londumas** [comment]
@cosmostatschool, thank you stranger :) @alxogm, could you review with yourself?

**Comment by alxogm** [comment]
> @cosmostatschool, thank you stranger :) @alxogm, could you review with yourself?
Done, sorry I accessed from a a different computer and was logged in with the other user. But I would thought this is not possible to do ....

**Comment by londumas** [comment]
@alxogm, thank you for the review.

**Pull request merged**
