### PR TITLE
preliminary support for using simqso to generate QSO templates

### PR DESCRIPTION
**Pull request by moustakas**
Not yet ready to merge as @imcgreer is continuing to add some requested changes to [simqso](https://github.com/imcgreer/simqso).  However, I would welcome comments (from anyone but especially QSO experts) on [the notebook](https://github.com/desihub/desisim/blob/simqso/doc/nb/simqso-templates.ipynb), which makes some preliminary comparisons with the existing QSO code.

### CODE REVIEW

**Comment by imcgreer** [comment]
See updated [notebook](https://github.com/imcgreer/simqso/blob/master/examples/quickspeclibrary.ipynb) now using DECam filters. For `ContinuumKCorr`, the two parameters specify the bandpass used for the apparent magnitudes (`obsBand`) and for the absolute magnitudes (`restBand`). In theory this should accept a wide range of inputs, in practice for now `obsBand` needs to be one of `SDSS-[ugriz]` and `restBand` needs to be a wavelength in Angstroms, i.e., 1450A. What I did is to add a hack to translate a given filter to SDSS, e.g., in the notebook the apparent magnitudes are based on `DECam-r` but the initial k-correction uses the effective wavelength for `SDSS-r`. This has little effect since the k-corrections are iterated until convergence in the correct band.

**Comment by imcgreer** [comment]
If you want to input both apparent mags and redshifts to `simqso`, instead of using `generateQlfPoints()` just create a grid with fixed input values. See the top of this [notebook](https://github.com/imcgreer/simqso/blob/master/examples/SimpleSpecExample.ipynb) (although that example uses `AbsMagVar`, it could also be `AppMagVar`).

**Comment by imcgreer** [comment]
@moustakas - if you add dust continuum on top of `get_BossDr9_model_vars()` you will get pretty wonky mid-IR colors. The BOSS DR9 continuum uses the broken power-law model from Glikman et al. out to ~3 um, and this power law is meant to approximate the dust bump at >1um. Adding `DustBlackbodyVar` on top of that basically adds the dust twice. I'm working on an improved continuum model with dust (see [here](https://github.com/imcgreer/simqso/blob/master/sdss/ebossmodels.py)) but surprisingly (to me) the BOSS DR9 hack is still performing better. I would suggest leaving the explicit addition of the dust bump out for now and just use the BOSS DR9 model as-is.

**Comment by moustakas** [comment]
This PR is getting incrementally closer but I need help adding [simqso](https://github.com/imcgreer/simqso) as an (optional?) dependence into desihub so the unit tests can be run.  @sbailey, @weaverba137 can either of you help as I'm not entirely sure how this should be done.

@imcgreer would you mind creating yet another tag of simqso so we're testing against a fixed version?  Also, if you have a moment, could you look at cell [11] of [this notebook](https://github.com/desihub/desisim/blob/simqso/doc/nb/simqso-templates.ipynb) and tell me why the Lyman-alpha forest doesn't always seem to kick in blueward of Lyman alpha?

**Comment by imcgreer** [comment]
This checkin imcgreer/simqso@4f286162f9c207b45f3335431663b68b233400b8 should fix the forest problem. Let me know if it works and if there aren't any further issues I can make a new tag.

**Comment by moustakas** [comment]
@imcgreer Thank you, your fix did work.  If you could make a new tag I'd be grateful.

**Comment by imcgreer** [comment]
v1.2.1 is now available.

**Comment by moustakas** [comment]
Shout-out to @imcgreer for all the help.  This PR doesn't have *all* the capabilities we need but I'll open up separate issues for those and so it's ready to be merged.

**Comment by julienguy** [comment]
This looks great. 
Is there a branch of simqso working with python3?
master branch of https://github.com/moustakas/simqso is python2.

**Comment by julienguy** [comment]
I found it's working fine with master version of https://github.com/imcgreer/simqso

**Comment by moustakas** [comment]
The master branch of `simqso` and `v1.2.1` (which is what I test against) is python3-compatible.

**Comment by moustakas** [comment]
Right, my fork of `simqso` is obsolete.  We need to discuss / decide whether we want to fork `simqso` into desihub or just require end-users to separately pip-install @imcgreer's master branch of `simqso`.  I'd be inclined to fork it so that we can package it into `desiconda` but implementing this shouldn't hold up this PR.

**Comment by julienguy** [comment]
I tested this successfully on edison. For me that's fine (continuing usage discussion by emails)

**Pull request merged**
