### PR TITLE
miscellaneous tweaks, mostly to templates.py

### PR DESCRIPTION
**Pull request by moustakas**
I need to merge a bunch of minor code enhancements, mostly in support of https://github.com/desihub/desitarget/issues/136.  I don't believe these changes affect any other work in progress...

[Note: this branch started out to address #203 but that original request doesn't match how the spectra are generated for the mocks.  Let's revisit that issue after I submit my `desitarget.mock` PR (coming soon).

### CODE REVIEW

**Comment by moustakas** [comment]
Some Travis tests are failing because they need an updated tag of `desiutil` (one which includes code added in https://github.com/desihub/desiutil/pull/54).  @weaverba137 or @sbailey could either of you cut a new tag of `desiutil` please (or am I allowed to?) and I'll update the `.travis.yml` file here.

**Comment by sbailey** [comment]
It's ok for desisim master to temporarily depend upon desiutil master, but we'll want to tag desiutil before the next tag of desisim so that the desisim tag doesn't depend upon a non-tag of desiutil.  I updated the .travis.yml file to use desiutil master for the tests for tonight.

**Comment by sbailey** [comment]
Changes look fine except that you accidentally added `doc/nb/.ipynb_checkpoints/mws-mock-checkpoint.ipynb` to the repo.  Please remove that.  If the Travis tests pass, go ahead and merge unless others have comments.

**Comment by moustakas** [comment]
Thanks @sbailey.  Regarding `doc/nb/.ipynb_checkpoints/mws-mock-checkpoint.ipynb` I actually *removed* that file, which I had added inadvertently in a previous PR (after which point I added `.ipynb_checkpoints` to the `.gitignore` file for this repository.  I'm merging this now and will update `.travis.yml` after `desiutil` has been tagged.

**Pull request merged**
