### PR TITLE
New quickcat interface

### PR DESCRIPTION
**Pull request by forero**
Here are some updatates to `quickcat`, as a first approximation to solve #182.

* `get_observed_redshifts_obsconditions` is a new function that uses a dictionary with `obsconditions` to estimate redshift success. It is based on Kyle's code. `quickcat.quickcat` now uses that function.
* `get_obsconditions` generates the `obsconditions` dictionary waiting for `surveysim` coupling.
* `get_observed_redshifts_zmag` is a place holder for a function that estimates redshift success based on true redshift and observed magnitudes. It is not used yet.

### CODE REVIEW

**Comment by sbailey** [comment]
I think we want each of the `get_observed_redshifts_*` functions to have the same inputs, whether that is tables of targets+fiberassign, truth, and obsconditions, or the individual columns pulled out into separate input arrays.  Some methods may ignore some variables/columns, but they should all have an identical call signature to make them easy to swap in and out for each other.

Similarly, they should all return the same thing: zobs, zerr, zwarn rather than just a probability for getting it right, since both "right" and "wrong" are ambiguous (what error? is wrong z with ZWARN != 0 right or wrong?  etc)

**Comment by forero** [comment]
Good. I will change the `get_observed_redshifts_` to have the same inputs. They all are already returning the same thing: zobs,zerr,zwarn.

**Comment by sbailey** [comment]
Clarification: I was getting mixed up between `get_redshift_efficiency_*` functions (which return a vector of probabilities) and the `get_observed_redshifts_*` functions that return `zobs, zerr, zwarn`.

**Comment by forero** [comment]
Got it. Will update this tomorrow. I will also add tests and wrap up the documentation to run the loop.

**Comment by forero** [comment]
@sbailey I made the updates to have an unified interface for those functions with/without obsconditions as input. Test pass and the loop on 400 deg^2 mock runs. What other tests do you have in mind?

**Comment by sbailey** [comment]
For the record, here is Kyle's original email about the model of redshift efficiencies vs. observing conditions, and the pdf attachment:

Following on the proposal from Tuesday's call, here is the implementation of correlated redshift errors for LRG, ELG, and QSO resulting from airmass, E(B-V), seeing, and atmospheric transmission.  I also added moon_fraction/moon_distance for the ELG sample (moon is below horizon for LRG/QSO).  The results from the five year survey using the output of Martin's code are attached.  I show the fractional change in redshift efficiency associated with each systematic, I require the average redshift efficiency to be 0.95, 0.9, and 0.8 for LRG, QSO, ELG, and I added a Gaussian random scatter in redshift success that is coherent across a full tile.  I did not implement radial, redshift or magnitude dependence on redshift efficiency, as those require individual objects.  Here, the scaling relations are all based on tile metadata.  I will do that, although not tonight.  I am not sending to the mailing list because that would publicize the solution to the systematic dependencies.

The algorithm is simple quadratic relationship on each parameter, where I made up the dependencies to be reasonable.  Jaime confirmed that it will be easy to implement in quickcat.  The exact dependencies I used are as follows:

;LRG
a=where(data.PROGRAM eq 'DARK')
lrg=data[a]

v=lrg.AIRMASS - mean(lrg.AIRMASS)
pv_lrg=1. + 0.15*v - 0.5*(v^2-mean(v^2))

w=lrg.EBMV - mean(lrg.EBMV)
pw_lrg=1. + 0.4*w 

x=lrg.seeing - mean(lrg.seeing)
px_lrg=1. + 0.06*x + 0.05*(x^2-mean(x^2))

y=lrg.lintrans - mean(lrg.lintrans)
py_lrg=1. + 0.08*(y^2-mean(y^2))

prandom_lrg=fltarr(n_elements(lrg))
for i=0,n_elements(lrg)-1 do prandom_lrg[i]=1.+0.02*randomn(lrg[i].TILEID)

p_lrg=0.95*pv_lrg*pw_lrg*px_lrg*py_lrg*prandom_lrg
a=where(p_lrg gt 1,count)
if count gt 0 then p_lrg[a] = 1.0


;QSO
a=where(data.PROGRAM eq 'DARK')
QSO=data[a]

v=qso.AIRMASS - mean(qso.AIRMASS)
pv_qso=1. - 0.2*v + 0.3*(v^2-mean(v^2))

w=qso.EBMV - mean(qso.EBMV)
pw_qso=1. - 0.5*w + 0.6*(w^2-mean(w^2))  

x=qso.seeing - mean(qso.seeing)
px_qso=1. - 0.1*x - 0.075*(x^2-mean(x^2))

y=qso.lintrans - mean(qso.lintrans)
py_qso=1. - 0.08*y - 0.04*(y^2-mean(y^2))

prandom_qso=fltarr(n_elements(qso))
for i=0,n_elements(qso)-1 do prandom_qso[i]=1.+0.05*randomn(qso[i].TILEID)

p_qso=0.9*pv_qso*pw_qso*px_qso*py_qso*prandom_qso
a=where(p_qso gt 1,count)
if count gt 0 then p_qso[a] = 1.0






;ELG
a=where(data.PROGRAM eq 'GRAY')
ELG=data[a]

v=elg.AIRMASS - mean(elg.AIRMASS)
pv_elg=1. - 0.1*v - 0.2*(v^2-mean(v^2))

w=elg.EBMV - mean(elg.EBMV)
pw_elg=1. + 0.25*w - 0.75*(w^2-mean(w^2))

x=elg.seeing - mean(elg.seeing)
px_elg=1. + 0.05*(x^2-mean(x^2))

y=elg.lintrans - mean(elg.lintrans)
py_elg=1. + 0.2*y + 0.1*(y^2-mean(y^2))

z=elg.MOONFRAC/elg.moondist - mean(elg.MOONFRAC/elg.moondist)
pz_elg=1. - 10.*z + 300.*(z^2-mean(z^2))

prandom_elg=fltarr(n_elements(elg))
for i=0,n_elements(elg)-1 do prandom_elg[i]=1.+0.075*randomn(elg[i].TILEID)

p_elg = 0.8 * px_elg * py_elg * pz_elg * prandom_elg
a=where(p_elg gt 1,count)
if count gt 0 then p_elg[a]=1.


[sim_z.pdf](https://github.com/desihub/desisim/files/622979/sim_z.pdf)

**Pull request merged**
