### PR TITLE
newexp-desi integrated with templates generated on-the-fly

### PR DESCRIPTION
**Pull request by moustakas**
I've tested the code, but independent eyes are welcome.  

The environment variables for all the individual target classes (DESI_ELG_TEMPLATES, DESI_LRG_TEMPLATES, etc.) are now obsolete.  All you need to set is
```
export DESI_BASIS_TEMPLATES=$DESI_ROOT/spectro/templates/basis_templates/v1.0
```

And then everything should "just work"
```
newexp-desi --nspec 500
```

FYI -- The following target classes are currently supported: ELG, LRG, QSO, STAR, STD (=FSTD), and WD.  In addition, BAD_QSO spectra are generated as interloper stars (although the stars don't yet satisfy the QSO color cuts.)

### CODE REVIEW

**Comment by moustakas** [comment]
For the ANL Workshop we might consider pre-building a handful (5-10) of fibermap & simspec files, each with 5000 spectra so that people can work on those output files with QuickGen directly.  Building the files isn't super-slow, but it's not lightning fast  either, largely because K-corrections have to be calculated for each object/spectrum before deciding whether the object passes the color-cuts.  (Interpolation/resampling is also slow.)

**Comment by sbailey** [comment]
I like the looks of this, and I like the suggestion of pre-building a handful of exposures to use at the Argonne workshop.  I think Govinda has been working on that using the current master using the data challenge 2 (dc2) templates.  I made a 0.5 tag of master as insurance, but I'd still like to try this end-to-end myself before merging it into master.  I probably won't merge tonight, but will try to get to it this weekend.

**Comment by sbailey** [comment]
Can you take a look at this, @moustakas?  It's not liking the D4000 metadata.

```
[edison ~] newexp-desi --nspec 500
INFO:io.py:600:read_basis_templates: Reading /project/projectdirs/desi/spectro/templates/basis_templates/v1.0/star_templates_v1.2.fits
Simulating FSTD template 10/10
INFO:io.py:600:read_basis_templates: Reading /project/projectdirs/desi/spectro/templates/basis_templates/v1.0/lrg_templates_v1.2.fits
Simulating LRG template 10/64
Simulating LRG template 20/64
Simulating LRG template 30/64
Simulating LRG template 40/64
Simulating LRG template 50/64
Simulating LRG template 60/64
Traceback (most recent call last):
  File "/global/homes/s/sjbailey/desi/git/desisim/bin/newexp-desi", line 80, in <module>
    tileid=opts.tileid, airmass=opts.airmass, exptime=opts.exptime)
  File "/global/homes/s/sjbailey/desi/git/desisim/py/desisim/obs.py", line 98, in new_exposure
    fibermap, truth = get_targets(nspec, tileid=tileid)
  File "/global/homes/s/sjbailey/desi/git/desisim/py/desisim/targets.py", line 180, in get_targets
    truth['D4000'][ii] = meta['D4000']
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/astropy-1.0.1_32b25281-7.1/lib/python2.7/site-packages/astropy-1.0.1-py2.7-linux-x86_64.egg/astropy/table/table.py", line 840, in __getitem__
    return self.columns[item]
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/astropy-1.0.1_32b25281-7.1/lib/python2.7/site-packages/astropy-1.0.1-py2.7-linux-x86_64.egg/astropy/table/table.py", line 107, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'D4000'
[edison ~] echo $DESIMODEL
/project/projectdirs/desi/software/edison/desimodel/0.3.8
[edison ~] echo $DESI_BASIS_TEMPLATES
/project/projectdirs/desi/spectro/templates/basis_templates/v1.0
[edison ~] echo $DESISPEC
/project/projectdirs/desi/software/edison/desispec/master
[edison ~] echo $DESISIM 
/global/homes/s/sjbailey/desi/git/desisim
[edison ~] cd $DESISIM; git branch
* desisim-templates
  edison-scaling
  master
  quickcat
```

**Comment by moustakas** [comment]
Oops, silly last-minute mistake.  Should be fixed now.  Here's the output on my laptop:
```
prometheus:ioannis% newexp-desi --nspec 500
INFO:io.py:600:read_basis_templates: Reading /Users/ioannis/research/projects/desi/spectro/templates/basis_templates/v1.0/star_templates_v1.2.fits
Simulating FSTD template 10/10
INFO:io.py:600:read_basis_templates: Reading /Users/ioannis/research/projects/desi/spectro/templates/basis_templates/v1.0/lrg_templates_v1.2.fits
Simulating LRG template 10/71
Simulating LRG template 20/71
Simulating LRG template 30/71
Simulating LRG template 40/71
Simulating LRG template 50/71
Simulating LRG template 60/71
Simulating LRG template 70/71
INFO:io.py:600:read_basis_templates: Reading /Users/ioannis/research/projects/desi/spectro/templates/basis_templates/v1.0/qso_templates_v1.1.fits
Simulating QSO template 10/46
Simulating QSO template 20/46
Simulating QSO template 30/46
Simulating QSO template 40/46
INFO:io.py:600:read_basis_templates: Reading /Users/ioannis/research/projects/desi/spectro/templates/basis_templates/v1.0/elg_templates_v1.4.fits
WARNING: UnitsWarning: 'erg/s/cm2' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
Simulating ELG template 10/324
Simulating ELG template 20/324
Simulating ELG template 30/324
Simulating ELG template 40/324
Simulating ELG template 50/324
Simulating ELG template 60/324
Simulating ELG template 70/324
Simulating ELG template 80/324
Simulating ELG template 90/324
Simulating ELG template 100/324
Simulating ELG template 110/324
Simulating ELG template 120/324
Simulating ELG template 130/324
Simulating ELG template 140/324
Simulating ELG template 150/324
Simulating ELG template 160/324
Simulating ELG template 170/324
Simulating ELG template 180/324
Simulating ELG template 190/324
Simulating ELG template 200/324
Simulating ELG template 210/324
Simulating ELG template 220/324
Simulating ELG template 230/324
Simulating ELG template 240/324
Simulating ELG template 250/324
Simulating ELG template 260/324
Simulating ELG template 270/324
Simulating ELG template 280/324
Simulating ELG template 290/324
Simulating ELG template 300/324
Simulating ELG template 310/324
Simulating ELG template 320/324
INFO:io.py:600:read_basis_templates: Reading /Users/ioannis/research/projects/desi/spectro/templates/basis_templates/v1.0/star_templates_v1.2.fits
/Users/ioannis/research/projects/desi/spectro/sim/debug/20151031/fibermap-00000008.fits
/Users/ioannis/research/projects/desi/spectro/sim/debug/20151031/simspec-00000008.fits
```

**Comment by gdhungana** [comment]
Looks good. I ran successfully in laptop. Sorry I was gone for APS last two days so couldn't update on time. @sbailey  Yes I'll upload bunch of files to quickCat area by tommorrow, that will be used for quickgen session and hopefully for redmonster session also. After this, is the wikipage(eg. QuickPipelineSimulation) and necessary files in nersc also going to change such that the environment variables etc are updated before workshop or we keep that as existing for now?  I doubt the template simulation will take place there anyway. 
@moustakas One thing I noticed for the simulation of templates is that every parameters like magnitude, redshift etc that could go  into the simulation function are taken as default for template  simulation right?, i.e That flexibility has not been propagated to newexp-desi and/or intermediate methods?

**Comment by moustakas** [comment]
@gdhungana Yes, the priors are currently fixed.  I couldn't think of a clean way to do this without weighing newexp-desi down with a ton of optional parameters.  One possibility would be to have the code read an optional (yaml) parameter file, but other suggestions are more than welcome.

Happy Halloween!

**Pull request merged**
