### PR TITLE
adds the option of including a Type Ia supernova spectrum in the BGS, ELG, and LRG spectra

### PR DESCRIPTION
**Pull request by moustakas**
Working closely with @orgraur we've implemented the option of including Type Ia supernova spectra (of varying epoch, or time since/after B-band maximum light) in the BGS, ELG, and LRG spectral classes. Right now this is implemented in a simplistic way whereby one simply specifies the r-band flux ratio of the  supernova with respect to the underlying galaxy, but we have a plan for properly sampling from a luminosity function.

A TechNote has been written (by Or) and will be posted shortly.

This PR adds just basic functionality for generating noiseless galaxy+supernova spectra. We still need to propagate this option to ```quickbrick``` (via a modified version of ```desisim.targets```) before full-scale simulations (e.g., to test supernova-extraction algorithms) can take place.

To generate 100 ELG models with supernovae simply do:
```
simulate-templates -n 100 -o ELG --add-SNeIa
```
or to specify the (flat) prior on the r-band flux ratio in some BGS spectra do
```
simulate-templates -n 100 -o BGS --sne-rfluxratiorange 0.05 0.5 --add-SNeIa
```

### CODE REVIEW

**Comment by sbailey** [comment]
This requires version 2.1 of DESI basis templates available at NERSC /project/projectdirs/desi/spectro/templates/basis_templates/v2.1/

If you urgently need this merged into master for some SRD prep or something, we could merge this now.  Otherwise, please:
* Add a lightweight version of these SNe basis templates to https://github.com/desihub/desisim-testdata by updating desisim-testdata/bin/trim_basis_templates to also trim the SNe templates
* Make a new tag of desisim-testdata
* Add unit tests to desisim to test the new galaxy+sne functionality
* Update desisim/etc/travis_env_common.sh to use the new desisim-testdata tag so that the Travis test will also work

If you have other ideas for how to simplify the synchronization between desisim-testdata and the latest templates and tests, let us know.  Thanks.

**Comment by moustakas** [comment]
The integration tests are still running, but I think I've satisfied all of @sbailey's requests.  The unit tests were also expanded to include the BGS templates (which they previously were not).

**Comment by sbailey** [comment]
The Travis tests timed out while reading the lite version of the SNe templates (or shortly thereafter).  I've restarted the test as a check, but it seems stuck in the same place. Can you confirm that the unit tests work for you when using desisim-testdata 0.2.1 as input rather than the full sized templates?

**Comment by moustakas** [comment]
On my laptop...
```
% setenv DESI_BASIS_TEMPLATES ~/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1
% python -m unittest desisim.test.test_templates.TestTemplates.test_sne
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/elg_templates_v2.0-lite.fits
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/sne_templates_v1.0-lite.fits
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/lrg_templates_v1.3-lite.fits
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/sne_templates_v1.0-lite.fits
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/bgs_templates_v2.0-lite.fits
INFO:io.py:459:read_basis_templates: Reading /Users/ioannis/desihub/desisim-testdata/desi/spectro/templates/basis_templates/v2.1/sne_templates_v1.0-lite.fits
.
----------------------------------------------------------------------
Ran 1 test in 3.853s

OK
```
Not sure how to diagnose this further but I'll keep trying.

**Comment by sbailey** [comment]
As a starter, check your package versions against the versions defined in .travis.yml and etc/travis_env_common.sh .  After a period of relative quiet, we may be due for another package incompatibility gotcha.

**Comment by moustakas** [comment]
My package versions are pretty close to those in .travis.yml.  I'll try to test with the precise versions tomorrow.  In the meantime I tried doing the tests locally with 
```
python setup.py test --coverage
```
and my python session crashes and then hangs. Not sure what's causing that, either.

**Comment by moustakas** [comment]
I'm still trying to figure out / debug why the travis builds aren't completing (any help or suggestions are welcome), but in the meantime this PR also fixes #115.

**Comment by sbailey** [comment]
`python setup.py test --coverage` hanging on your local machine seems the route to chase.

Another data point but not an answer: both `python setup.py test` and `python setup.py test --coverage` work for me using desisim-testdata/0.2.1, numpy/1.10.4, scipy/0.17.0, astropy/1.1.1, python/2.7.11, nose/1.3.3, coverage/3.7.1.  (most of these determined with "import blat; print blat.\_\_version\_\_")

What versions do you have locally?

**Comment by weaverba137** [comment]
I think the Travis tests are failing because one of the install scripts performs a `cd` to another directory and doesn't `cd` back to the original directory, containing the setup.py file.

**Comment by weaverba137** [comment]
In travis_env_common.sh, you do `cd ./data` to install desisim-testdata.  However, you've removed the data directory.  So `cd ./data` fails, desisim-testdata gets installed in the wrong place, *and* as a bonus, you then do `cd ..` which takes you to a directory that doesn't contain setup.py, because you never successfully `cd`ed to a subdirectory.  A trifecta of pain, sorry to say.

**Comment by moustakas** [comment]
Thank you @weaverba137 for the sleuthing.  And @sbailey I also debugged why the original Travis tests weren't passing -- I was adding such a strong SN contribution that the ELGs were never passing the color-cuts!  This is ready to merge.

**Pull request merged**
