### PR TITLE
updated stellar templates to have much finer coverage of physical parameters

### PR DESCRIPTION
**Pull request by moustakas**
Add support for new (v3.0) stellar templates (documented in #423) with a new detailed notebook:
https://github.com/desihub/desisim/blob/stars-v3.0/doc/nb/star-templates.ipynb

Tests won't pass until I update the `desisim-testdata` repository but wanted to get this in now.

Many thanks to Carlos Allende Prieto for his help with this over the past few weeks.

### CODE REVIEW

**Comment by moustakas** [comment]
Once tests pass (they should!) this PR is ready to be merged.  

The code changes here are *not* backwards-compatible because the new stellar templates only extend to ~1 micron, so anyone doing spectral simulations on their laptop needs to get the latest set of `$DESI_BASIS_TEMPLATES`, which was bumped to version `v3.0`.   See [SimulatingDESIdata](https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata) for details.

@sbailey @weaverba137 I updated the `desisim/etc/desisim.module` file here but you need to cast a spell at NERSC to make sure the correct environment variable gets set.

I'll send a note on-list as well, but there were updates to nearly all the template classes, especially the stars and LRGs (hence the big bump to 3.0).  Briefly (quoting from the README):

* bal_templates_v2.1.fits - Add correct EXTNAME to metadata table header.

* bgs_templates_v2.2.fits - Update metadata to include synthesized BASS+MzLS
  photometry.  Add SED-fitting quantities to the metadata table (SFR100, SFRAGE,
  etc.).  Add EXTNAME to all headers.

* elg_templates_v2.1.fits - Update metadata to include synthesized BASS+MzLS
  photometry.  Add SED-fitting quantities to the metadata table (SFR100, SFRAGE,
  etc.).  Add EXTNAME to all headers.

* lrg_templates_v2.1.fits - Major update to LRG templates based on latest LRG
  selection and DR7 photometry.  Use empirical weights to ensure the models are
  statistically representative of the parent (photometric) LRG sample.  Update
  metadata table to include synthesized BASS+MzLS photometry.  Add EXTNAME to
  all headers.

* sne_templates_v1.1.fits - Add EXTNAME to all headers.

* star_templates_v3.0.fits - Significantly expanded stellar template set.  Much finer
  binning in physical parameter space at the expense of shorter wavelength
  coverage (~1 micron vs ~6 micron for the v2.2 templates).

There is a companion (imminent) `desitarget/bin/select_mock_targets` PR which makes use of these new templates.

**Comment by moustakas** [comment]
Thanks to @sbailey for asking (off-list) for a clarification about backwards-compatibility.

Contrary to what I wrote at the top of this thread, `desisim.templates` *is* backwards-compatible with older templates (definitely `>v2.0`, although I haven't tested earlier versions), so no deprecation warnings are necessary.  

On the other hand `desitarget/bin/select_mock_targets` is *not* backwards-compatible with the older templates (see https://github.com/desihub/desitarget/pull/395), but very few people run that particular piece of code (and those that do should be using the latest template set).

Related to this PR but unrelated to the previous comment: with the new stellar templates one thing we should revisit is https://github.com/desihub/desispec/issues/264, updating the stellar templates we use for flux calibration.

Unless there are any other suggestions or reviews of the code I'll plan on merging this later today.

**Comment by weaverba137** [comment]
Someone will have to make sure that the master module files are hand-edited with the updates.

**Comment by moustakas** [comment]
> Someone will have to make sure that the master module files are hand-edited with the updates.

Thanks, @weaverba137.  Is this something you can do after this has been merged?  @sbailey is at a review today (and maybe tomorrow?).

Also, I'm trying to test the instructions
https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata
and can't seem to export the latest tagged templates over the network.  Is this something you or someone else can independently test, to see if it's an issue on my end?

```
% svn export svn+ssh://ioannis@dtn01.nersc.gov/global/projecta/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/tags/v3.0
svn: E170013: Unable to connect to a repository at URL 'svn+ssh://ioannis@dtn01.nersc.gov/global/projecta/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/tags/v3.0'
svn: E210002: Network connection closed unexpectedly
```

[Note that we previously had the wrong path to the basis templates on the wiki page---we were pointing to `/global/projecta/projectdirs/desi/spectro/templates/calib`, not `/global/projecta/projectdirs/desi/spectro/templates/basis_templates`.

**Pull request merged**
