### PR TITLE
update template/simspec metadata data model

### PR DESCRIPTION
**Pull request by moustakas**
This PR addresses #290 with a major (and backwards-incompatible) change to how the template/simulated metadata are returned by the various `desisim.templates` classes, and written in the `simspec` files.   

This is still a work in progress (~one more day) but I wanted @sbailey to take an early look since he's simultaneously updating the fibermap data model, which will touch several of the same routines.  This change will also affect the Lya WG via changes to `quickquasars` (see below).

Some new features:
* The `TRUTH` metadata table is significantly simpler in that it only contains objtype-agnostic information, e.g.,
```
['TARGETID', 'OBJTYPE', 'SUBTYPE', 'TEMPLATEID', 'SEED', 'REDSHIFT', 'MAG', 'MAGFILTER',
 'FLUX_G', 'FLUX_R', 'FLUX_Z', 'FLUX_W1', 'FLUX_W2']
```
* We now write out objtype-specific metadata, depending on the mix of object types (linked via their unique `TARGETID`), e.g., for STDs in the `TRUTH_STD` extension the columns are simply:
```
['TARGETID', 'TEFF', 'LOGG', 'FEH']
```
* I have added a `MAGFILTER` column indicating the spectrum normalization filter (corresponding to `MAG`) (previously the filter was not discoverable from the data themselves), which is also needed to deal with the north/south split in our photometry.
* A metadata table for BALs in correctly constructed and populated in `templates.QSO` and returned.
* The `SIMQSO` metadata (not a simple astropy Table) are properly written out and read back in for reproducibility (however, [this bug](https://github.com/imcgreer/simqso/issues/26) will need to be fixed first.

Still to do:
- [ ] Add arguments to synthesize photometry and apply target selection cuts separately for DECaLS vs MzLS/BASS (i.e., south vs north) photometry.
- [ ] Update `scripts.quickspectra.sim_spectra` and the routines that call it (e.g., `quickquasars`).
- [ ] Restore support for (re)generating templates using the `input_meta` argument.
- [ ] Update code related to `desitarget/bin/select_mock_targets`, which will be done in a separate PR.

Finally, note that the simulated simspec files are comparable in size to previously generated files:  there are now additional HDUs and a replicated `TARGETID` but the change in file size is not significant.  In addition, `desisim.io.read_simspec` can still read in old-style simspec files without error.

### CODE REVIEW

**Comment by moustakas** [comment]
With these additional commits:

- [x] Add arguments to synthesize photometry and apply target selection cuts separately for DECaLS vs MzLS/BASS (i.e., south vs north) photometry.
- [x] Update scripts.quickspectra.sim_spectra and the routines that call it (e.g., quickquasars).
- [x] Restore support for (re)generating templates using the input_meta argument.

Note that for the galaxy classes (ELG, LRG, and BGS) the velocity dispersion is not longer stored in the metadata table---it has to be passed as an additional argument if one wants to (re)generate spectra from a given `input_meta` table.  I *think* this only affects `desitarget/bin/select_mock_targets`.

Also note that this PR depends on the simqso bugfixes just merged in https://github.com/imcgreer/simqso/pull/28.  Finally, the support for inserting type Ia SNe is still broken, but I'll tackle that next.

@sbailey If you're inspired to start testing the way the new code changes interface with the `simspec` files that'd be very helpful.  

Please do not merge yet as I am sure there are still undiscovered problems.

**Comment by moustakas** [comment]
@weaverba137 Apologies in advance for what is likely to be a trivial fix, but I can't get tests to run because Travis fails to pip-install `simqso`, e.g., 
https://travis-ci.org/desihub/desisim/jobs/423142296

Meanwhile, on my laptop I have no issues installing (seemingly) using the same command:
```
conda create -n junk python=3 numpy scipy astropy
source activate junk
pip install git+https://github.com/imcgreer/simqso.git@v1.2.3#egg=simqso
```

Thanks.

**Comment by weaverba137** [comment]
It looks like the conda install did not successfully install numpy.  This may be due to a temporary glitch.  I suggest restarting the test.  If the problem persists, try setting DEBUG=True in the .travis.yml file.

**Comment by moustakas** [comment]
@weaverba137 Sorry, I'm still not having any luck.  I'd be grateful for any suggestions.

**Comment by weaverba137** [comment]
PS, for dealing with the first issue, you don't actually *need* to install simqso for the `egg_info` and `bdist_egg` tests.

**Comment by moustakas** [comment]
I fixed some of the most obvious failing tests but have no idea what's causing the "indentation error" when building sphinx documentation.  Any help would be welcome.

> PS, for dealing with the first issue, you don't actually need to install simqso for the egg_info and bdist_egg tests.

Offhand I don't know how to address this issue.

Some additional failures seem to be happening because of an issue with `ci-helpers` (see [this](https://github.com/desihub/desitarget/pull/364#issuecomment-418748296) comment by @weaverba137), so we're stuck waiting for that to be resolved.

Since this was such a large refactor there may be some lurking bugs and downstream issues. In particular, I've broken support for including supernovae in the templates (note to @sybenzvi), but I intend to fix that in a separate branch.

Otherwise this PR should be ready to be merged.

**Comment by weaverba137** [comment]
The conda version problem has returned.  I'm in touch with astropy folks.

**Comment by moustakas** [comment]
@weaverba137 Can I work on the non-conda failures now?

**Comment by weaverba137** [comment]
Well, that depends.  As long as you are running tests offline, go ahead.  But right now there is no guarantee that any Travis test will succeed.  In any case, I'm only modifying the .travis.yml file, nothing else.

**Comment by moustakas** [comment]
@weaverba137 I'll push my changes after you're done, but FYI all tests pass on my laptop now.

**Comment by weaverba137** [comment]
@moustakas, I'm handing this back to you.  All remaining test failures are due to actual problems in desisim code, not any conda install or fitsio problems.

**Comment by weaverba137** [comment]
The trick to pip installing master is to *not* specify a version.  Alternatively, you could specify a particular commit that happens to be on the master branch.

**Comment by weaverba137** [comment]
I think we have a winner...

**Comment by moustakas** [comment]
Merging now before Travis changes its mind....  Thank you @weaverba137!

**Pull request merged**
