### PR TITLE
Quickgen specsim

### LINKED ISSUE #44: Migrate desisim to use specsim instead of quicksim
This will involve changes to some code and the desisim dependencies.

### PR DESCRIPTION
**Pull request by dkirkby**
This PR is to merge PR #56 into master and fixes #44.

### CODE REVIEW

**Comment by dkirkby** [comment]
@rstaten Can you give me a command-line I can use to test `quickgen` in your new branch?  This didn't work:
```
desisim% quickgen --nspec 10
Need Fibermap file
```
Is there an easy way to give it a valid fibermap (on my laptop) ?

**Comment by rstaten** [comment]
@dkirkby quickgen --simspec simspec-00000002.fits --fibermap fibermap-00000002.fits --nspec 7

**Comment by dkirkby** [comment]
I don't already have a file called `fibermap-00000002.fits`, so that fails.

**Comment by rstaten** [comment]
[simspec-00000002.fits.zip](https://github.com/desihub/desisim/files/70165/simspec-00000002.fits.zip)
[fibermap-00000002.fits.zip](https://github.com/desihub/desisim/files/70166/fibermap-00000002.fits.zip)

**Comment by dkirkby** [comment]
Thanks, that works for me and I am merging now.

**Pull request merged**
