### PR TITLE
new LRG templates

### PR DESCRIPTION
**Pull request by moustakas**
(This PR can await the tagging that's happening today -- it just contains a notebook.)

I've generated a new set of empirical LRG templates based on the new LRG selection criteria, as fully described in [this notebook](https://github.com/desihub/desisim/blob/lrg-templates/doc/nb/lrg-templates.ipynb).  

I still need to update `desisim-testdata` and the templates themselves are still being uploaded to NERSC but they should appear in 
  /global/project/projectdirs/desi/spectro/templates/basis_templates/v2.4
soon.

Comments are welcome.

### CODE REVIEW

**Comment by moustakas** [comment]
@weaverba137 / @sbailey  I'm having trouble updating the svn template repo at NERSC.  Hopefully the traceback below is sufficient.  Any thoughts?

```bash
ioannis@cori10:~/desi/spectro/templates/basis_templates/basis_templates_svn/trunk% pwd
/global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/trunk
ioannis@cori10:~/desi/spectro/templates/basis_templates/basis_templates_svn/trunk% svn up
svn: E155036: Please see the 'svn upgrade' command
svn: E155036: The working copy at '/global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn'
is too old (format 29) to work with client version '1.8.10 (r1615264)' (expects format 31). You need to upgrade the working copy first.

ioannis@cori10:~/desi/spectro/templates/basis_templates/basis_templates_svn/trunk% svn upgrade
svn: E155019: Can't upgrade '/global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/trunk' as it is not a working copy root
svn: E000002: Working copy database '/global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/trunk/.svn/wc.db' not found
svn: E000002: Additional errors:
svn: E000002: Can't open file '/global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn/trunk/.svn/entries': No such file or directory
```

**Comment by weaverba137** [comment]
Try it now.  The .svn/ directory is in /global/project/projectdirs/desi/spectro/templates/basis_templates/basis_templates_svn, and that's where you need to run `svn upgrade`.  I've already run it.

**Comment by moustakas** [comment]
Thanks @weaverba137!

**Comment by moustakas** [comment]
I'm going to merge this now although I defer to either @sbailey or @weaverba137 to update the `DESI_BASIS_TEMPLATES` environment variable at NERSC to point to the new basis templates (`v2.4`), which I've tagged in the svn repo.   

There's no rush on this, however.

**Pull request merged**
