### PR TITLE
Fix dlabugs

### PR DESCRIPTION
**Pull request by alxogm**
Fixes a couple of issues when adding DLAs. Tested running in full London mock.

### CODE REVIEW

**Comment by alxogm** [comment]
@julienguy @moustakas  whenever you have a chance to check this PR, it fixes the issue that was making the full simulations to stop. I've ran a full simulation without crashing. thanks

**Comment by alxogm** [comment]
@julienguy I've move it after args.nmax, that makes sense, thanks. But I'm not sure about moving it after target selection. This is a comment from @andreufont  from sometime ago, when I asked where it was best to add them:

"What is important is that you need to add them before you do your final normalization to match a given magnitude, since DLAs make the quasars fainter, and before you applied target selection."

**Comment by julienguy** [comment]
Thanks.
I committed one modification (write the DLA meta data even if no zbest file, I think it was a typo).
I'll merge as soon as the Travis tests are done.

**Comment by julienguy** [comment]
Travis failures have nothing to do with this PR
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/desi_test_io/spectro/sim/test-quickgen/20150105/00000100/fibermap-00000100.fits'
```

**Comment by julienguy** [comment]
I cannot reproduce the error. Tests are passing without problem at NERSC. I think this is a Travis I/O issue. I am merging so that we can move forward.

**Comment by julienguy** [comment]
the I/O issues are due to the desispec changes with raw data and fibermap under NIGHT/EXPID/ not just NIGHT/. this is solved when merging the other desisim mockobs pull request.

**Pull request merged**
