### PR TITLE
Desisim metalfactor 

### PR DESCRIPTION
**Pull request by Andrea-MG**
Update of new metal COEF values:
SiII(1260), SiIII(1207), SiII(1193), SiII(1190), OVI(1032), OVI(1038), CIV(1548), and CIV(1550)
-AndreaMG

### CODE REVIEW

**Comment by londumas** [comment]
@Andrea-MG, could you add a plot giving the relation between bias and metal coef?

**Comment by londumas** [comment]
@Andrea-MG, I don't understand these values. I though we had concluded that `SiII(1260)` was too high, that we should lower the coef... I am confused.

**Comment by Andrea-MG** [comment]
I attach the plot used.

bias_COEF

**Comment by Andrea-MG** [comment]
It is smaller, If I am correct the previous value was 8.e-4, the one I computed is 3.542e-5

**Comment by Andrea-MG** [comment]
I believe my git push had a mistake. One sec!

**Comment by Andrea-MG** [comment]
Indeed. Fixed!

**Comment by londumas** [comment]
@Andrea-MG, looks good. Let's send a test with the different updated lines in v6 and see if everything is ok. Then we will merge.

**Comment by londumas** [comment]
@Andrea-MG, looks good. Let's compute one, hopefully, last correlation with high SNR to confirm the lines.

**Comment by londumas** [comment]
@Andrea-MG, you will have to merge your branch with master to solve the Travis error It should be something like that.
```
git checkout desisim_metalfactor
git pull
git merge master
git push
```

**Comment by Andrea-MG** [comment]
The latest values for the best fit parameters are:

bias_eta_LYA          | -0.162        | 0.00478  
bias_eta_SiII(1190) | -0.000573  | 0.000489 |
bias_eta_SiII(1193) | -0.00161    | 0.000472 |
bias_eta_SiII(1260) | -1.63E-08   | 0.00247  |
bias_eta_SiIII(1207) | -0.00217   | 0.000483 |

And the 3dcf wedges obtained, compared to DR14 data:
image
image

**Comment by londumas** [comment]
@Andrea-MG, Thank you. Can you try to fix the merging conflict, if you can't @alxogm or me can have a look.

**Comment by Andrea-MG** [comment]
@londumas I am giving it a try!

**Comment by Andrea-MG** [comment]
@londumas ready! Is everything ok now?

**Comment by londumas** [comment]
@Andrea-MG, perfect Thank you I am merging now.

**Pull request merged**
