### PR TITLE
Documentation fixes

### LINKED ISSUE #222: fix desisim API documentation
I would like to get started with desisim, but I couldn't find documentation. If I go to 
http://desisim.readthedocs.io/en/latest/api.html
I get a bunch of error messages. Is it only me, or is the API documentation broken?

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Fixes a number of documentation problems that were preventing API documentation from building successfully.
* Closes #222 

**Do not merge yet!**  Although most of the fixes are already in, I need to verify that ReadTheDocs is also working.

### CODE REVIEW

**Comment by weaverba137** [comment]
This branch's documentation now compiles with no errors. See http://desisim.readthedocs.io/en/documentation-fixes/api.html

**Comment by weaverba137** [comment]
This is ready to merge.  You can inspect the API documentation at the link in the previous comment.

**Comment by sbailey** [comment]
Thanks for this cleanup.  I'll merge after Travis tests finish running (or go ahead and merge if you see them finish and I haven't gotten back here to do it).

Could you post how you sent the documentation for a branch to desisim.readthedocs.io ?

Note: This PR gets us back to a clean state for updating the documentation (thanks!), but we have more work to do after this PR to address the new-user "where do I start" kind of documentation.

**Comment by weaverba137** [comment]
Last minute change: update changes.rst.

I was able to add the branch to readthedocs because I "own" it.  That is, I have a personal account on readthedocs, and most of the DESI documentation is operated through that account.  We've talked about this before, but we never got around to creating a shared account for Travis/Coveralls/Readthedocs.

**Comment by weaverba137** [comment]
I will merge this shortly.  In the meantime, I've had an idea of how to implement documentation failure detection in Travis without all the astropy paraphernalia.

**Pull request merged**
