### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by sbailey**
This PR updates desisim to be compatible with both python 3.5 and 2.7; it requires the recently minted desispec 0.10.0 and desiutil 1.8.0.

@weaverba137 and/or others — please review and comment.

Full disclosure: I had to loosen the tolerance on the DECAM_FLUX check when testing that we get the same templates back when providing a metadata table.  It is still close enough agreement that it doesn't really matter on a practical level, but the disagreement is much worse than machine precision so it is slightly concerning.  This is a known issue after @moustakas last refactor; we may need to chase this down later.

### CODE REVIEW

**Comment by sbailey** [comment]
I'll need a new version of specsim for this to work with the Travis tests, since the latest tag of specsim isn't yet compatible with py3.5 (master is, but not v0.4).  I'll ping @dkirkby .

**Comment by dkirkby** [comment]
I just tagged and released specsim v0.5: [docs](http://specsim.readthedocs.io/en/stable/) | [pypi](https://pypi.python.org/pypi/specsim/0.5).

**Comment by sbailey** [comment]
Thanks for the specsim/v0.5 release, which the travis tests now use.  Travis tests now pass on py 2.7 and 3.5; this PR is ready for final review @weaver and/or others.

**Comment by weaverba137** [comment]
This looks good to me.

**Pull request merged**
