### PR TITLE
quicksurvey on surveysim outputs

### PR DESCRIPTION
**Pull request by forero**
This PR has a new version of `quicksurvey` running on `surveysim` outputs. It now requires as an input an `exposures` file (a `surveysim` output) and a list of dates to run `fiberassign`.

### CODE REVIEW

**Comment by forero** [comment]
Travis tests are failing with 
`ImportError: No module named 'fitsio'`
How can that this be fixed?

**Comment by sbailey** [comment]
fitsio was already in .travis.yml for the code tests, but needed to be added to doc/conf.py autodoc_mock_imports for the sphinx documentation build to work without having fitsio installed.

Are the instructions in https://github.com/desihub/quicksurvey_example still valid for running this version of quicksurvey?  If not, could you post a simple example of what to run to test this?  Code itself looks fine, but I'd prefer to actually run it once at NERSC prior to merging.

**Comment by forero** [comment]
Good. I will update the instructions.

**Comment by sbailey** [comment]
checking in: I don't see updated instructions, but am I looking in the wrong place?

**Comment by forero** [comment]
I haven't updated the instructions. I got derailed by other things. I am back in track today.

**Comment by forero** [comment]
Updated instructions are now in this [separate pull request](https://github.com/desihub/quicksurvey_example/pull/13)

**Comment by forero** [comment]
Just rebased from master because I needed to recreate target selection with the latest data model.

**Pull request merged**
